# Generated by Django 5.0.8 on 2025-09-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_channel', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram-канал')),
                ('google_form_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Form')),
                ('education_materials', models.TextField(blank=True, null=True, verbose_name='Обучающие материалы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
