# Generated by Django 5.0.8 on 2025-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usercabinet'),
        ('content', '0011_educationmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercabinet',
            options={'verbose_name': 'Кабинет пользователя', 'verbose_name_plural': 'Кабинеты пользователей'},
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='users', to='content.projects'),
        ),
        migrations.RemoveField(
            model_name='usercabinet',
            name='education_materials',
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='education_materials',
            field=models.ManyToManyField(blank=True, related_name='cabinets', to='content.educationmaterial', verbose_name='Обучающие материалы'),
        ),
    ]
