version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8000"
    volumes:
      - ./back_media:/app/back_media
      - ./back_static:/app/back_static
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./back_media:/app/back_media
      - ./back_static:/app/back_static
    depends_on:
      - web
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./back_media:/app/back_media
      - ./back_static:/app/back_static
    depends_on:
      - web
