services:
  
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - .:/app
      - ./back_static:/app/config/back_static
      - ./back_media:/app/back_media
      - ./sqlite_data:/app/sqlite_data   
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.settings
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      # Если нужно для Swagger локально:
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1,http://localhost
    depends_on:
      - postgres # Ждем, пока база поднимется
    restart: always
    networks:
      - webnet

  nginx:
    image: linuxserver/swag
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bishkek
      - URL=jashtar-kyimyly.pp.ua
      - SUBDOMAINS=api,www
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false
      - STAGING=false
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl.conf:/config/nginx/site-confs/ssl/ssl.conf
      - ./nginx/nginx.conf:/config/nginx/site-confs/default.conf
      - ./back_static:/app/back_static
      - ./back_media:/app/back_media
      - lets:/config/etc/letsencrypt/
    restart: always
    networks:
      - webnet

# Регистрация всех сетей и томов (здесь были ошибки)
networks:
  webnet:
    driver: bridge

volumes:
  sqlite_data:
  lets:
  pgdata: # Вот он, том для Postgres, из-за которого падала первая ошибка!