version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - .:/app
      - ./back_static:/app/back_static
      - ./back_media:/app/back_media
      - ./sqlite_data:/app/sqlite_data   # папка для хранения sqlite базы
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    restart: always
    networks:
      - webnet

  nginx:
    image: linuxserver/swag
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bishkek
      - URL=jashtar-kyimyly.pp.ua
      - SUBDOMAINS=api,www
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false
      - STAGING=false
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl.conf:/config/nginx/site-confs/ssl/ssl.conf
      - ./nginx/nginx.conf:/config/nginx/site-confs/default.conf
      - ./back_static:/app/back_static
      - ./back_media:/app/back_media
      - lets:/config/etc/letsencrypt/
    restart: always
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  sqlite_data:
  lets:
