# Generated by Django 5.0.8 on 2025-09-08 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg', upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Цели и миссия',
                'verbose_name_plural': 'Цели и миссия',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg', upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'История создания',
                'verbose_name_plural': 'История создания',
            },
        ),
        migrations.CreateModel(
            name='Legislative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(max_length=155, verbose_name='Название закона')),
                ('law_ru', models.CharField(max_length=155, null=True, verbose_name='Название закона')),
                ('law_en', models.CharField(max_length=155, null=True, verbose_name='Название закона')),
                ('law_ky', models.CharField(max_length=155, null=True, verbose_name='Название закона')),
                ('file', models.FileField(blank=True, help_text='Загружайте файлы только в формате .pdf, .word, или .excel', null=True, upload_to='research/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'word', 'excel'])], verbose_name='Файлы')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg', upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Законодательная база',
                'verbose_name_plural': 'Законодательная база',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .jpeg, .png или .jpg', upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])], verbose_name='Изображение')),
                ('full_name', models.CharField(max_length=155, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=155, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=155, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=155, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=155, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=155, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Руководство',
                'verbose_name_plural': 'Руководство',
            },
        ),
    ]
