# Generated by Django 5.0.8 on 2025-09-29 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_direction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Фотография')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about_direction.goals', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Фотография цели',
                'verbose_name_plural': 'Фотографии цели',
            },
        ),
    ]
