# Generated by Django 5.0.8 on 2025-10-01 00:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_direction', '0002_goalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Фотография')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about_direction.history')),
            ],
            options={
                'verbose_name': 'Фотография истории создания',
                'verbose_name_plural': 'Фотографии истории создания',
            },
        ),
    ]
