# Generated by Django 5.0.8 on 2025-10-01 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_direction', '0003_historyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislative',
            name='image',
        ),
        migrations.AddField(
            model_name='legislative',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='legislative',
            name='description',
            field=models.CharField(default='', max_length=155, verbose_name='Описание закона'),
        ),
    ]
