# Generated by Django 5.0.8 on 2025-10-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_direction', '0005_management_department'),
        ('content', '0007_activitydirection_short_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='content.departments', verbose_name='Отделение'),
        ),
    ]
