# Generated by Django 5.0.8 on 2025-10-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_direction', '0006_alter_management_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='department',
        ),
    ]
