# Generated by Django 5.0.8 on 2025-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_direction', '0007_remove_management_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislative',
            name='description_en',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='Описание закона'),
        ),
        migrations.AddField(
            model_name='legislative',
            name='description_ky',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='Описание закона'),
        ),
        migrations.AddField(
            model_name='legislative',
            name='description_ru',
            field=models.CharField(default='', max_length=155, null=True, verbose_name='Описание закона'),
        ),
    ]
