upstream jashtar_server {
    server jashtar_backend:8000;
}

server {
    listen 80;
    client_max_body_size 20M;

    location /admin/ {
        proxy_pass http://jashtar_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /back_static/ {
        alias /opt/services/jashtar-kyimyly-backend/back_static/;
    }

    location /back_media/ {
        alias /opt/services/jashtar-kyimyly-backend/back_media/;
    }

    location /api/ {
        proxy_pass http://jashtar_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
