# Generated by Django 5.0.8 on 2026-04-05 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=155, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('description_ky', models.CharField(max_length=155, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О движении',
                'verbose_name_plural': 'О движении',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название баннера')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название баннера')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название баннера')),
                ('title_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название баннера')),
                ('description', models.CharField(max_length=255, verbose_name='Текстовое описание')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Текстовое описание')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Текстовое описание')),
                ('description_ky', models.CharField(max_length=255, null=True, verbose_name='Текстовое описание')),
                ('cta_text', models.CharField(default='Вступить в движение', max_length=255, verbose_name='Текст кнопки (СТА)')),
                ('cta_text_ru', models.CharField(default='Вступить в движение', max_length=255, null=True, verbose_name='Текст кнопки (СТА)')),
                ('cta_text_en', models.CharField(default='Вступить в движение', max_length=255, null=True, verbose_name='Текст кнопки (СТА)')),
                ('cta_text_ky', models.CharField(default='Вступить в движение', max_length=255, null=True, verbose_name='Текст кнопки (СТА)')),
                ('cta_link', models.URLField(verbose_name='Ссылка на Google Forms')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='home', unique=True, verbose_name='Связка')),
                ('home_title', models.CharField(max_length=155, verbose_name='Название главной страницы')),
                ('home_title_ru', models.CharField(max_length=155, null=True, verbose_name='Название главной страницы')),
                ('home_title_en', models.CharField(max_length=155, null=True, verbose_name='Название главной страницы')),
                ('home_title_ky', models.CharField(max_length=155, null=True, verbose_name='Название главной страницы')),
                ('banner', models.CharField(max_length=155, verbose_name=' Банер')),
                ('banner_ru', models.CharField(max_length=155, null=True, verbose_name=' Банер')),
                ('banner_en', models.CharField(max_length=155, null=True, verbose_name=' Банер')),
                ('banner_ky', models.CharField(max_length=155, null=True, verbose_name=' Банер')),
                ('about_movent', models.CharField(max_length=166, verbose_name=' О движении')),
                ('about_movent_ru', models.CharField(max_length=166, null=True, verbose_name=' О движении')),
                ('about_movent_en', models.CharField(max_length=166, null=True, verbose_name=' О движении')),
                ('about_movent_ky', models.CharField(max_length=166, null=True, verbose_name=' О движении')),
                ('events', models.CharField(max_length=155, verbose_name='Мероприятия')),
                ('events_ru', models.CharField(max_length=155, null=True, verbose_name='Мероприятия')),
                ('events_en', models.CharField(max_length=155, null=True, verbose_name='Мероприятия')),
                ('events_ky', models.CharField(max_length=155, null=True, verbose_name='Мероприятия')),
                ('news', models.CharField(max_length=155, verbose_name='Новости')),
                ('news_ru', models.CharField(max_length=155, null=True, verbose_name='Новости')),
                ('news_en', models.CharField(max_length=155, null=True, verbose_name='Новости')),
                ('news_ky', models.CharField(max_length=155, null=True, verbose_name='Новости')),
                ('brend_material', models.CharField(max_length=155, verbose_name='Бренд материал')),
                ('brend_material_ru', models.CharField(max_length=155, null=True, verbose_name='Бренд материал')),
                ('brend_material_en', models.CharField(max_length=155, null=True, verbose_name='Бренд материал')),
                ('brend_material_ky', models.CharField(max_length=155, null=True, verbose_name='Бренд материал')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('text', models.TextField(max_length=400, verbose_name='Описание')),
                ('text_ru', models.TextField(max_length=400, null=True, verbose_name='Описание')),
                ('text_en', models.TextField(max_length=400, null=True, verbose_name='Описание')),
                ('text_ky', models.TextField(max_length=400, null=True, verbose_name='Описание')),
                ('about_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_movement', to='home.aboutmovement')),
            ],
            options={
                'verbose_name': 'Карточки о движении',
                'verbose_name_plural': 'Карточки о движении',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Загружайте только изображения в формате .svg', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Изображение (SVG)')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='home.banner')),
            ],
            options={
                'verbose_name': 'Изображение баннера',
                'verbose_name_plural': 'Изображения баннеров',
            },
        ),
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Изображение')),
                ('data', models.DateField()),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('short_text', models.TextField(max_length=255, verbose_name='Короткий текст')),
                ('short_text_ru', models.TextField(max_length=255, null=True, verbose_name='Короткий текст')),
                ('short_text_en', models.TextField(max_length=255, null=True, verbose_name='Короткий текст')),
                ('short_text_ky', models.TextField(max_length=255, null=True, verbose_name='Короткий текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_items', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Карточка мероприятия',
                'verbose_name_plural': 'Карточки мероприятий',
            },
        ),
        migrations.CreateModel(
            name='BrendMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brend_material/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('price', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brend_items', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Бренд материал',
                'verbose_name_plural': 'Бренд материалы',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Banner', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='aboutmovement',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_movement', to='home.homepage'),
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_image', models.ImageField(upload_to='news/', verbose_name='Изображения новостей')),
                ('data', models.DateField()),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('description_ru', models.TextField(max_length=255, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(max_length=255, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(max_length=255, null=True, verbose_name='Описание')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
