# Generated by Django 5.0.8 on 2025-09-08 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=155, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('description_ky', models.CharField(max_length=155, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О движении',
                'verbose_name_plural': 'О движении',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Преимущество')),
                ('text_ru', models.TextField(max_length=400, null=True, verbose_name='Преимущество')),
                ('text_en', models.TextField(max_length=400, null=True, verbose_name='Преимущество')),
                ('text_ky', models.TextField(max_length=400, null=True, verbose_name='Преимущество')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Текстовое описание')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Текстовое описание')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Текстовое описание')),
                ('description_ky', models.CharField(max_length=255, null=True, verbose_name='Текстовое описание')),
                ('cta_text', models.CharField(default='Вступить в движение', max_length=255, verbose_name='Текст кнопки (СТА)')),
                ('cta_text_ru', models.CharField(default='Вступить в движение', max_length=255, null=True, verbose_name='Текст кнопки (СТА)')),
                ('cta_text_en', models.CharField(default='Вступить в движение', max_length=255, null=True, verbose_name='Текст кнопки (СТА)')),
                ('cta_text_ky', models.CharField(default='Вступить в движение', max_length=255, null=True, verbose_name='Текст кнопки (СТА)')),
                ('cta_link', models.URLField(verbose_name='Ссылка на Google Forms')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='BrandMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название материала')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название материала')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название материала')),
                ('file', models.FileField(help_text='Допустимые форматы: jpg, jpeg, png, pdf, svg', upload_to='brand_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'svg'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Бренд-материал',
                'verbose_name_plural': 'Бренд-материалы',
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Загружайте только изображения в формате .svg', upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Изображение (SVG)')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='home.banner')),
            ],
            options={
                'verbose_name': 'Изображение баннера',
                'verbose_name_plural': 'Изображения баннеров',
            },
        ),
    ]
