# Generated by Django 5.0.8 on 2026-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.FileField(upload_to='banners/', verbose_name='Изображение '),
        ),
    ]
