# Generated by Django 5.0.8 on 2025-10-02 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_brandmaterial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание материала'),
        ),
        migrations.CreateModel(
            name='BrandMaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Допустимые форматы: jpg, jpeg, png, pdf, svg', upload_to='brand_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'svg'])], verbose_name='Изображение')),
                ('brand_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.brandmaterial')),
            ],
            options={
                'verbose_name': 'Изображение материала',
                'verbose_name_plural': 'Изображения материала',
            },
        ),
    ]
