# Generated by Django 5.0.8 on 2025-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_brandmaterial_description_brandmaterialimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название баннера'),
        ),
    ]
