# Generated by Django 5.0.8 on 2025-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название баннера'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название баннера'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название баннера'),
        ),
    ]
