upstream jashtar_server {
    server jashtar_backend:8000;
}

server {
    server_name jashtarkyimyly.kg;
    client_max_body_size 64M;

    location * {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        add_header 'Access-Control-Expose-Headers' 'Authorization' always;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            add_header 'Access-Control-Max-Age' 86400 always;
            add_header 'Content-Length' 0 always;
            return 204;
        }
        if ($request_method = 'POST') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        }
        if ($request_method = 'GET') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
        }
    }
    
    location / {
      index index.html;
      root /opt/services/mountain_view_frontend/build;
      try_files $uri $uri/ /index.html;
    }

    location /admin/ {
        proxy_pass http://jashtar_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /opt/services/jashtar-kyimyly-backend/back_static/;
    }

    location /media/ {
        alias /opt/services/jashtar-kyimyly-backend/back_media/;
    }

    location /api/ {
        proxy_pass http://jashtar_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    location /docs/ {
        proxy_pass http://jashtar_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /redoc/ {
        proxy_pass http://jashtar_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/jashtarkyimyly.kg/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jashtarkyimyly.kg/privkey.pem;
}
server {
    if ($host = jashtarkyimyly.kg) {
        return 301 https://$host$request_uri;
    }

    if ($host = www.jashtarkyimyly.kg) {
        return 301 https://$host$request_uri;
    }

    server_name jashtarkyimyly.kg;
    return 404;
}