# Generated by Django 5.0.8 on 2025-08-28 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название направления')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название направления')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название направления')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название направления')),
                ('description', models.TextField(verbose_name='Описание деятельности')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание деятельности')),
                ('description_en', models.TextField(null=True, verbose_name='Описание деятельности')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание деятельности')),
            ],
            options={
                'verbose_name': 'Направление деятельности',
                'verbose_name_plural': 'Направление деятельности',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название отделения')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название отделения')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название отделения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=99, verbose_name='Адрес отделения')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg или .jpeg', upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Региональные отделения',
                'verbose_name_plural': 'Региональные отделения',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название мероприятия')),
                ('title_ru', models.CharField(max_length=99, null=True, verbose_name='Название мероприятия')),
                ('title_en', models.CharField(max_length=99, null=True, verbose_name='Название мероприятия')),
                ('title_ky', models.CharField(max_length=99, null=True, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание мероприятия')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание мероприятия')),
                ('description_en', models.TextField(null=True, verbose_name='Описание мероприятия')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание мероприятия')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('event_status', models.CharField(choices=[('upcoming', 'Предстоящие'), ('past', 'Прошедшие')], max_length=255, verbose_name='Статус мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=99, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=99, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=99, null=True, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg или .jpeg', upload_to='experts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Изображение')),
                ('title', models.CharField(max_length=99, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=99, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=99, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=99, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название проекта')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название проекта')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название проекта')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание проекта')),
                ('description_en', models.TextField(null=True, verbose_name='Описание проекта')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание проекта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.TextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.TextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.TextField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Результаты',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='VideoArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название видеоматериала')),
                ('title_ru', models.CharField(max_length=99, null=True, verbose_name='Название видеоматериала')),
                ('title_en', models.CharField(max_length=99, null=True, verbose_name='Название видеоматериала')),
                ('title_ky', models.CharField(max_length=99, null=True, verbose_name='Название видеоматериала')),
                ('video_url', models.URLField(validators=[django.core.validators.URLValidator(regex='^https?://(www\\.)?(youtube\\.com|youtu\\.be)/.+$', schemes=['https'])], verbose_name='Ссылка на видеоматериал')),
            ],
            options={
                'verbose_name': 'Видеоархив',
                'verbose_name_plural': 'Видеоархивы',
            },
        ),
        migrations.CreateModel(
            name='DepartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фотография')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.departments', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Фотография отделения',
                'verbose_name_plural': 'Фотографии отделения',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фотография')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.events', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Фотография мероприятия',
                'verbose_name_plural': 'Фотографии мероприятия',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фотография')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фотография галереи',
                'verbose_name_plural': 'Фотографии галереи',
            },
        ),
        migrations.CreateModel(
            name='ProjectsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фотография')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проекта',
            },
        ),
    ]
