# Generated by Django 5.0.8 on 2025-10-01 12:30

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_events_slug_remove_news_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.CharField(default='Улица, дом', max_length=155, verbose_name='Местоположение мероприятия'),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default=content.models.current_time, verbose_name='Время'),
        ),
    ]
