# Generated by Django 5.0.8 on 2025-10-01 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_events_place_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата изображений'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=125, null=True, verbose_name='Название изображения'),
        ),
    ]
