# Generated by Django 5.0.8 on 2025-10-02 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_galleryimage_date_galleryimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydirection',
            name='image',
            field=models.ImageField(default='bebebe', help_text='Загружайте только изображения в формате .png или .jpg или .jpeg', upload_to='activity-directions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='activitydirection',
            name='instagram_link',
            field=models.CharField(blank=True, default='https://example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='activitydirection',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activitydirection',
            name='telegram_link',
            field=models.CharField(blank=True, default='https://example.com', max_length=255),
        ),
    ]
