# Generated by Django 5.0.8 on 2025-10-02 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_activitydirection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydirection',
            name='image',
            field=models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg или .jpeg', upload_to='activity-directions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='activitydirection',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Короткое описание направления'),
        ),
    ]
