# Generated by Django 5.0.8 on 2025-10-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_activitydirection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydirection',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое описание направления'),
        ),
        migrations.AddField(
            model_name='activitydirection',
            name='short_description_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое описание направления'),
        ),
        migrations.AddField(
            model_name='activitydirection',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Короткое описание направления'),
        ),
    ]
