# Generated by Django 5.0.8 on 2025-10-02 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_activitydirection_short_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО сотрудника')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО сотрудника')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО сотрудника')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция сотрудника')),
                ('position_ru', models.CharField(max_length=100, null=True, verbose_name='Позиция сотрудника')),
                ('position_en', models.CharField(max_length=100, null=True, verbose_name='Позиция сотрудника')),
                ('position_ky', models.CharField(max_length=100, null=True, verbose_name='Позиция сотрудника')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='content.departments', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
