# Generated by Django 5.0.8 on 2025-10-02 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Цели проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='goals_en',
            field=models.TextField(blank=True, null=True, verbose_name='Цели проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='goals_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Цели проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='goals_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Цели проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to='project_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Главная фотография'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks_en',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Задачи проекта'),
        ),
    ]
