# Generated by Django 5.0.8 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_projects_goals_projects_goals_en_projects_goals_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='title_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Название изображения'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Название изображения'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Название изображения'),
        ),
    ]
