# Generated by Django 5.0.8 on 2025-10-06 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_galleryimage_title_en_galleryimage_title_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('title_ru', models.CharField(max_length=155, null=True)),
                ('title_en', models.CharField(max_length=155, null=True)),
                ('title_ky', models.CharField(max_length=155, null=True)),
                ('attachment_type', models.CharField(choices=[('document', 'DOCUMENT'), ('video', 'VIDEO'), ('link', 'LINK')], default='document', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Загружайте документы (.pdf, .docx, .txt) или видео (.mp4, .mov, .avi)', null=True, upload_to='education_materials/', verbose_name='Вложение')),
                ('link', models.URLField(blank=True, help_text='Если тип вложения LINK, вставьте ссылку сюда', max_length=500, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
