# Generated by Django 5.0.8 on 2025-10-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_educationmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmaterial',
            options={'verbose_name': 'Обучающий материал', 'verbose_name_plural': 'Обучающие материалы'},
        ),
    ]
