# Generated by Django 5.0.8 on 2025-10-06 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_educationmaterial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmaterial',
            name='attachment_type',
            field=models.CharField(choices=[('document', 'DOCUMENT'), ('video', 'VIDEO'), ('link', 'LINK')], default='document', max_length=20, verbose_name='Тип вложения'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='link',
            field=models.URLField(blank=True, help_text='Если тип вложения link, вставьте ссылку сюда', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='title_ky',
            field=models.CharField(max_length=155, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationmaterial',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Название'),
        ),
    ]
