# Generated by Django 5.0.8 on 2025-10-10 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_educationmaterial_attachment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, help_text='Загружайте только изображения в формате .png или .jpg или .jpeg', upload_to='employees/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Фото сотрудника'),
        ),
    ]
