# Generated by Django 5.0.8 on 2025-10-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='image',
        ),
        migrations.DeleteModel(
            name='DepartmentImage',
        ),
    ]
