# Generated by Django 5.0.8 on 2025-10-11 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_departments_image_delete_departmentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название')),
                ('image', models.ImageField(help_text='Загружайте только изображения в формате .png или .jpg или .jpeg', upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=155, verbose_name='Описание')),
                ('description_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Описание')),
                ('description_ky', models.CharField(blank=True, max_length=155, null=True, verbose_name='Описание')),
                ('link', models.URLField(help_text='Если тип вложения link, вставьте ссылку сюда', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка')),
            ],
        ),
    ]
