# Generated by Django 5.0.8 on 2025-10-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
