# Generated by Django 5.0.8 on 2025-10-11 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка'),
        ),
    ]
